### ISSUE TITLE
Essai pour voir si tout le monde peut accéder aux issues

### ISSUE THREAD

**Issue by maelvalais** [FredMaris/touist#125]
Coucou @Illurian, @kreole, @Adriusse

Juste un test pour voir si tout le monde reçoit bien les mails quand on vous mentionne dans une issue. 

Pouvez-vous poster un message sur cet issue pour m'indiquer que tout fonctionne bien ?
- soit en répondant au mail directement,
- soit en allant sur la page de l'issue

D'ailleurs il manque l'un de vous quatre sur le dépôt. Vu que vos noms ne sont pas mentionnés, je ne sais pas qui est qui :unamused: 

À vendredi :smiley:

**Comment by kreole** [comment]
Bien reçu :) 

Et oui je vois qu'il manque, Dorian SEPULCRE. Il doit faire une demande sur le github à FredMaris, pour qu'il le rajoute ? 

A vendredi

**Comment by maelvalais** [comment]
@kreole merci pour ta réponse :grinning:. Connais-tu son username github ?

**Comment by Adriusse** [comment]
Moi cest Adriusse :D

Adrien ESCOURROU

----- Mail d'origine -----De: Ma&euml;l Valais <notifications@github.com>&Agrave;: FredMaris/touist <touist@noreply.github.com>Cc: Adriusse <ad.escourrou@laposte.net>Envoy&eacute;: Fri, 18 Mar 2016 10:42:12 +0100 (CET)Objet: [touist] Essai pour voir si tout le monde peut acc&eacute;der aux issues (#125)

Coucou @Illurian, @kreole, @Adriusse
Juste un test pour voir si tout le monde re&ccedil;oit bien les mails quand on vous mentionne dans une issue.
Pouvez-vous poster un message sur cet issue pour m'indiquer que tout fonctionne bien ?

soit en r&eacute;pondant au mail directement,
soit en allant sur la page de l'issue

D'ailleurs il manque l'un de vous quatre sur le d&eacute;p&ocirc;t. Vu que vos noms ne sont pas mentionn&eacute;s, je ne sais pas qui est qui 
&Agrave; vendredi 
&mdash;You are receiving this because you were mentioned.Reply to this email directly or view it on GitHub

**Comment by maelvalais** [comment]
@Adriusse Possible d'ajouter ton nom dans ton profil github ? Ça m'aidera pour faire le lien ^^

@kreole Possible de demander à Dorian de se créer un compte github et de nous indiquer son username ?

Bon WE à tous ! :relaxed:

**Comment by Adriusse** [comment]
Fait !

----- Mail d'origine -----De: Ma&euml;l Valais <notifications@github.com>&Agrave;: FredMaris/touist <touist@noreply.github.com>Cc: Adriusse <ad.escourrou@laposte.net>Envoy&eacute;: Sat, 19 Mar 2016 12:12:13 +0100 (CET)Objet: Re: [touist] Essai pour voir si tout le monde peut acc&eacute;der aux issues (#125)

@Adriusse Possible d'ajouter ton nom dans ton profil github ? &Ccedil;a m'aidera pour faire le lien ^^
@kreole Possible de demander &agrave; Dorian de se cr&eacute;er un compte github et de nous indiquer son username ?
Bon WE &agrave; tous ! 
&mdash;You are receiving this because you were mentioned.Reply to this email directly or view it on GitHub

**Comment by maelvalais** [comment]
Ça c'est du rapide ^^

**Comment by maelvalais** [comment]
@FredMaris Pouraris-tu ajouter "dodo64" au projet ? Il s'agit de Dorian Sepulcre :smile:
